baseURL: https://schollsebastian.com/hugo-demo/
languageCode: de-at
title: Leonie
theme: ananke

menu:
  main:
  - name: team
    URL: /team/
    weight: 100
  - name: architektur
    URL: /architecture/
    weight: 110
