baseURL: https://schollsebastian.com/hugo-demo/
languageCode: de-at
title: Leonie
theme: leonie

menu:
  main:
  - name: leonie
    URL: /
    weight: 90
  - name: team
    URL: /team/
    weight: 100
  - name: architektur
    URL: /architecture/
    weight: 110
  - name: neuigkeiten
    URL: /post/
    weight: 120
